package main

const (
	LOG_LEVEL_DEBUG = iota
	LOG_LEVEL_INFO
	LOG_LEVEL_WARN
	LOG_LEVEL_ERROR
	LOG_LEVEL_FATAL
)

const (
	EVENT_SERVER_STARTED = iota
	EVENT_REQUEST_RECEIVED
	EVENT_BACKEND_SELECTED
	EVENT_REQUEST_COMPLETED
	EVENT_BACKEND_HEALTH_CHANGED
	EVENT_BACKEND_ADDED
	EVENT_BACKEND_REMOVED
	EVENT_PROXY_ERROR_GENERIC
	EVENT_PROXY_ERROR_STARTUP
)
